application:
  name: abn-api

server:
  port: 8080
  shutdown: graceful
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never
    include-exception: false

spring:
#  profiles:
#    active: dev
  flyway:
    locations:
      - /db/migration/common
      - ${environment-specific-flyway-migrations}
  datasource:
    url: jdbc:h2:mem:abndb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
      format_sql: false
      dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false

springdoc:
  swagger-ui:
    path: /abn-api
